Dev new match
GengGode/cvAutoTrack pull request #98
Opened 2024-01-16 02:46 UTC by Sallee1

2024-01-16 02:52 UTC, GengGode commented on include/cvAutoTrack.h
> +#ifdef _DEBUG
re

2024-01-16 02:52 UTC, GengGode commented on include/cvAutoTrack.h
> +#endif
```suggestion
#endif
```

2024-01-16 03:10 UTC, GengGode requested changes

2024-01-16 03:10 UTC, GengGode commented on include/cvAutoTrack.h
> +#ifdef _DEBUG
```suggestion
```

2024-01-16 03:10 UTC, GengGode commented on include/cvAutoTrack.h
> +#endif
```suggestion
```

2024-01-16 03:10 UTC, GengGode commented on include/cvAutoTrack.h
> +#endif
不需要在头文件里宏判断

2024-01-16 03:10 UTC, GengGode commented on include/cvAutoTrack.h
> +extern "C" bool CVAUTOTRACK_API LoadDbgMapImg(const char* path);
```suggestion
extern "C" bool CVAUTOTRACK_API DebugLoadMapImagePath(const char* path);
```
不要缩写

2024-01-16 03:10 UTC, GengGode commented on source/AutoTrack.cpp
> +#ifdef _DEBUG
```suggestion
```

2024-01-16 03:10 UTC, GengGode commented on source/AutoTrack.cpp
> +#endif // _DEBUG
```suggestion
```

2024-01-16 03:10 UTC, GengGode commented on source/AutoTrack.cpp
> +    res.DbgMap = cv::imread(path);
```
#ifdef _DEBUG
    res.DbgMap = cv::imread(path);
    return true;
#else
    return false;
#endif
```

2024-01-16 03:10 UTC, GengGode commented on source/AutoTrack.h
> +    bool LoadDbgMapImg(const char* path);
```suggestion
```
这种辅助函数别放到at类里了

2024-01-16 03:10 UTC, GengGode commented on source/cvAutoTrack.cpp
> +#ifdef _DEBUG
这个函数整体迁移到module.debug.cpp里

2024-01-16 03:10 UTC, GengGode commented on source/utils/Utils.cpp
> +    cv::Point2d transform(cv::Point2d pos, cv::Point2d origin, double scale)
必须要传递一个变量进来，那就没必要做成静态函数，直接结构体的成员函数就好了 features.transfer_to()的俩重载
如果是返回一个新的变量那就_to如果是改变自己就不带to

2024-01-16 03:54 UTC, Alex-Beng commented on source/match/surf/SurfMatch.cpp
> +    cv::Mat trans_mat = cv::findHomography(matched_keypoints_object, matched_keypoints_scene,out_mask,cv::RANSAC,10);
可以考虑换成estimateAffinePartial2D试试效果，用法见 [gist](https://gist.github.com/Alex-Beng/995802cd49d158132f3a3e38e1186bd3#file-contours_ransac-cpp-L161).

2024-01-16 04:08 UTC, GengGode commented on source/algorithms/features/features.operate.h
> +    //转换features的坐标系，先平移，再缩放
```
struct features
{
...    
void transform(const cv::Point2f &origin, const double scale)
    {
        for (auto &keypoint : this.keypoints)
            keypoint.pt = cv::Point2d((keypoint.pt - origin) * scale);
    }
};
```

2024-01-16 05:12 UTC, GengGode commented on source/algorithms/algorithms.include.cpp
不要单独开个cpp，直接放到h里加inline

2024-01-16 05:43 UTC, GengGode commented on source/cvAutoTrack.cpp
>  #endif // _DEBUG
这个宏记得删

2024-01-16 17:17 UTC, Sallee1 commented on source/match/surf/SurfMatch.cpp
> +    cv::Mat trans_mat = cv::findHomography(matched_keypoints_object, matched_keypoints_scene,out_mask,cv::RANSAC,10);
已替换，并且预先变换小地图的关键点，这样就可以直接从mat里拿坐标了

2024-01-17 03:43 UTC, GengGode commented on source/algorithms/algorithms.include.h
> +    inline void TransformAxes(const cv::Point2f &origin, const double scale)
变换轴的意思怪怪的，transform就够了吧，或者是transform_features_postions

2024-01-17 03:43 UTC, GengGode commented on source/module.debug.h
> +namespace tianli::debug {
module里的是不是不用套一层命名空间了

2024-01-17 08:07 UTC, GengGode approved these changes

2024-01-17 08:07 UTC, merged